// ════════════════════════════════════════════════════════════════════
// ui/academy/academy-data.js  — VD ACADEMY ders verisi (Phase 1)
//
// Statik içerik kaynağı. window.VDAcademyData = { categories, lessons }.
// Her ders: { id, title, cat, level, short, chart, trader, mistake, events }
//   level : 'temel' | 'orta' | 'ileri'
//   events: bağlı Timeline event türleri (etiket) — event-lesson-map ile eşleşir
// Eğitim amaçlıdır; yatırım tavsiyesi değildir.
// ════════════════════════════════════════════════════════════════════
(function () {
  'use strict';

  const categories = [
    { id: 'formasyon', label: 'Formasyonlar', icon: '📐' },
    { id: 'smc',       label: 'Smart Money Concepts', icon: '💧' },
    { id: 'gosterge',  label: 'Teknik Göstergeler', icon: '📊' },
    { id: 'futures',   label: 'Futures Temelleri', icon: '⚙️' },
    { id: 'yapi',      label: 'Market Yapısı', icon: '🏛️' },
  ];

  const L = (o) => o; // kısa yardımcı

  const lessons = [
    // ── 1. FORMASYONLAR ──────────────────────────────────────────────
    L({ id:'obo', title:'Omuz Baş Omuz', cat:'formasyon', level:'orta',
      short:'Yükseliş trendinin sonunda görülen, üç tepeden oluşan dönüş formasyonu.',
      chart:'Ortadaki tepe (baş) iki yandaki tepelerden (omuzlar) daha yüksektir. Omuzların diplerini birleştiren "boyun çizgisi" kırıldığında formasyon teyit olur.',
      trader:'Yükselişin bittiğine ve aşağı dönüşe geçilebileceğine dair güçlü bir ipucu sayılır.',
      mistake:'Boyun çizgisi kırılmadan formasyonu "tamamlandı" saymak. Teyit olmadan pozisyon almak erken karardır.',
      events:['Risk','Breakout'] }),
    L({ id:'ters-obo', title:'Ters Omuz Baş Omuz', cat:'formasyon', level:'orta',
      short:'Düşüş trendinin sonunda görülen, üç dipten oluşan yukarı dönüş formasyonu.',
      chart:'Ortadaki dip (baş) en derindir; iki yandaki dipler (omuzlar) daha sığdır. Boyun çizgisi yukarı kırıldığında teyit olur.',
      trader:'Düşüşün zayıfladığına ve yukarı dönüş ihtimaline işaret edebilir.',
      mistake:'Hacim teyidi olmadan kırılıma güvenmek. Zayıf hacimli kırılımlar sahte olabilir.',
      events:['Breakout'] }),
    L({ id:'cekic', title:'Çekiç Mum', cat:'formasyon', level:'temel',
      short:'Düşüşün dibinde oluşan, uzun alt fitilli, küçük gövdeli dönüş mumu.',
      chart:'Gövde mumun üst kısmındadır, alt fitil gövdenin en az iki katıdır. Satıcıların aşağı ittiği ama alıcıların geri topladığı anlamına gelir.',
      trader:'Dip bölgesinde alıcı ilgisinin döndüğüne dair erken bir sinyal olabilir.',
      mistake:'Tek bir çekiç mumu kesin dönüş sanmak. Teyit için sonraki mumu beklemek gerekir.',
      events:['Liquidity','Smart Money'] }),
    L({ id:'ters-cekic', title:'Ters Çekiç', cat:'formasyon', level:'temel',
      short:'Düşüş sonrası oluşan, uzun üst fitilli küçük gövdeli mum.',
      chart:'Gövde altta, üst fitil uzundur. Alıcıların yukarı denediği ama henüz teyit gelmediği bir geçiş mumudur.',
      trader:'Olası dönüşün habercisi olabilir ama tek başına zayıf bir sinyaldir.',
      mistake:'Ters çekici tepe formasyonu (shooting star) ile karıştırmak. Konum (dip mi tepe mi) belirleyicidir.',
      events:['Liquidity'] }),
    L({ id:'yutan', title:'Yutan Mum (Engulfing)', cat:'formasyon', level:'temel',
      short:'Önceki mumun gövdesini tamamen kapsayan ters yönlü güçlü mum.',
      chart:'Boğa yutan: küçük kırmızı mumun ardından onu tümüyle saran büyük yeşil mum. Ayı yutan tam tersi.',
      trader:'Yön değişiminde momentumun el değiştirdiğine işaret edebilir.',
      mistake:'Sadece gövdeye bakıp hacmi göz ardı etmek. Hacimsiz yutan mum güvenilmezdir.',
      events:['Momentum','Smart Money'] }),
    L({ id:'doji', title:'Doji', cat:'formasyon', level:'temel',
      short:'Açılış ve kapanışın neredeyse eşit olduğu kararsızlık mumu.',
      chart:'Çok küçük veya neredeyse yok gövde, iki yanda fitiller. Alıcı ve satıcının dengelendiğini gösterir.',
      trader:'Trendin duraksadığına; devam veya dönüş öncesi kararsızlığa işaret eder.',
      mistake:'Her doji\'yi dönüş sanmak. Doji tek başına yön vermez, bağlam şarttır.',
      events:['Momentum'] }),
    L({ id:'ucgen', title:'Üçgen Formasyonları', cat:'formasyon', level:'orta',
      short:'Fiyatın daralan bir aralıkta sıkıştığı, kırılım öncesi yapı.',
      chart:'Yükselen, alçalan veya simetrik üçgen. Tepe ve dipler birbirine yaklaşır; kırılım genelde sıkışma sonunda gelir.',
      trader:'Yaklaşan büyük hareketin habercisidir; yön kırılımla belli olur.',
      mistake:'Kırılım yönünü önceden tahmin edip erken girmek. Üçgen yön vermez, kırılım verir.',
      events:['Squeeze','Breakout'] }),
    L({ id:'bayrak', title:'Bayrak / Flama', cat:'formasyon', level:'orta',
      short:'Güçlü bir hareketin ardından gelen kısa soluklanma ve devam formasyonu.',
      chart:'Sert yükseliş/düşüş (direk) sonrası küçük eğimli kanal (bayrak) veya küçük üçgen (flama). Trend yönünde kırılır.',
      trader:'Mevcut trendin devam etme ihtimaline işaret eden bir dinlenme molasıdır.',
      mistake:'Bayrağı dönüş sanmak. Bayrak genelde trend yönünde devam eder.',
      events:['Momentum','Breakout'] }),
    L({ id:'ikili-tepe', title:'İkili Tepe', cat:'formasyon', level:'orta',
      short:'Aynı seviyede iki kez test edilen tepe; aşağı dönüş formasyonu.',
      chart:'İki benzer yükseklikte tepe ("M" şekli), aradaki dibin (boyun) kırılması teyit verir.',
      trader:'Direncin aşılamadığına ve satış baskısının arttığına işaret eder.',
      mistake:'İki tepe görünce hemen short açmak. Boyun çizgisi kırılmadan teyit yoktur.',
      events:['Equal High','Risk'] }),
    L({ id:'ikili-dip', title:'İkili Dip', cat:'formasyon', level:'orta',
      short:'Aynı seviyede iki kez test edilen dip; yukarı dönüş formasyonu.',
      chart:'İki benzer derinlikte dip ("W" şekli), aradaki tepenin kırılması teyit verir.',
      trader:'Desteğin korunduğuna ve alıcı ilgisinin döndüğüne işaret edebilir.',
      mistake:'İkinci dibin ilkinden belirgin aşağıda olmasını göz ardı etmek — o zaman formasyon bozulur.',
      events:['Equal Low'] }),

    // ── 2. SMART MONEY CONCEPTS ──────────────────────────────────────
    L({ id:'bos', title:'BOS — Break of Structure', cat:'smc', level:'ileri',
      short:'Mevcut trend yönünde bir önceki tepe/dibin kırılması; trendin devamı.',
      chart:'Yükselişte son tepenin yukarı kırılması (HH), düşüşte son dibin aşağı kırılması (LL) BOS sayılır.',
      trader:'Trendin hâlâ güçlü ve geçerli olduğunu teyit eder.',
      mistake:'Her küçük kırılımı BOS sanmak. Anlamlı yapı seviyeleri kullanılmalı.',
      events:['BOS','Breakout'] }),
    L({ id:'choch', title:'CHoCH — Change of Character', cat:'smc', level:'ileri',
      short:'Trendin karakterinin değiştiği ilk kırılım; olası dönüşün erken işareti.',
      chart:'Yükselişte ilk kez bir önceki dibin aşağı kırılması (veya tersi). BOS\'un aksine trend YÖNÜNE karşı gelir.',
      trader:'Trendin zayıflayıp dönebileceğine dair ilk uyarıdır.',
      mistake:'CHoCH\'u kesin dönüş sanmak. Teyit için yapı değişiminin devamı gerekir.',
      events:['CHoCH'] }),
    L({ id:'order-block', title:'Order Block', cat:'smc', level:'ileri',
      short:'Kurumsal emirlerin yoğunlaştığı, sert hareket öncesi son zıt yönlü mum bölgesi.',
      chart:'Güçlü yükseliş öncesi son düşüş mumu (boğa OB) veya tersi. Fiyat geri döndüğünde tepki verebilir.',
      trader:'Akıllı paranın bıraktığı izlerin tepki/giriş bölgesi olabileceğini gösterir.',
      mistake:'Her mumu order block ilan etmek. OB, belirgin dengesizlik (impulse) ile birlikte anlamlıdır.',
      events:['Order Block','Smart Money'] }),
    L({ id:'fvg', title:'Fair Value Gap (FVG)', cat:'smc', level:'ileri',
      short:'Üç mumda oluşan, fiyatın hızlı geçtiği ve sonradan doldurmaya eğilimli boşluk.',
      chart:'Orta mumun fitillerinin yan mumlarla örtüşmediği boşluk. Fiyat genelde bu boşluğu test etmeye döner.',
      trader:'Dengesizliğin bulunduğu, geri çekilmede tepki beklenebilecek bölgedir.',
      mistake:'Her FVG\'nin mutlaka dolacağını varsaymak. Bazıları uzun süre dolmaz.',
      events:['FVG','Smart Money'] }),
    L({ id:'liquidity-sweep', title:'Liquidity Sweep', cat:'smc', level:'ileri',
      short:'Likidite bölgesinin kısa süreli test edilip ters yöne dönülmesi.',
      chart:'Önce son tepe/dip aşılır (stoplar tetiklenir), ardından hızlı geri dönüş olur.',
      trader:'Stop avı veya yön dönüşü ihtimali anlamına gelebilir.',
      mistake:'Her fitil liquidity sweep değildir; hacim ve bağlam olmadan yorumlamak yanıltır.',
      events:['Liquidity','Risk','Smart Money'] }),
    L({ id:'equal-high', title:'Equal High (Eşit Tepe)', cat:'smc', level:'orta',
      short:'Aynı seviyede oluşan tepeler; üstünde likidite biriken bölge.',
      chart:'Yan yana benzer yükseklikte tepeler. Üstlerinde stop emirleri toplanır, hedef likidite olabilir.',
      trader:'Fiyatın bu seviyeyi süpürmeye (sweep) gelebileceğine işaret eder.',
      mistake:'Eşit tepeyi kesin direnç sanmak; çoğu zaman likidite avı için kırılır.',
      events:['Equal High','Liquidity'] }),
    L({ id:'equal-low', title:'Equal Low (Eşit Dip)', cat:'smc', level:'orta',
      short:'Aynı seviyede oluşan dipler; altında likidite biriken bölge.',
      chart:'Benzer derinlikte dipler. Altlarında stoplar toplanır, sweep hedefi olabilir.',
      trader:'Fiyatın bu dibi süpürüp dönme ihtimaline işaret eder.',
      mistake:'Eşit dibi kesin destek saymak; likidite için aşağı süpürülebilir.',
      events:['Equal Low','Liquidity'] }),
    L({ id:'stop-hunt', title:'Stop Hunt', cat:'smc', level:'ileri',
      short:'Yoğun stop bölgelerinin kasıtlı tetiklenmesiyle oluşan kısa, sert hareket.',
      chart:'Belirgin seviye hızlıca aşılır, stoplar tetiklenir, sonra fiyat ters döner.',
      trader:'Zorla çıkarılan pozisyonlar ardından yön dönüşü gelebilir.',
      mistake:'Stop hunt\'ı normal kırılımla karıştırıp trend yönünde girmek.',
      events:['Risk','Liquidity'] }),

    // ── 3. TEKNİK GÖSTERGELER ───────────────────────────────────────
    L({ id:'rsi', title:'RSI', cat:'gosterge', level:'temel',
      short:'0–100 arası momentum göstergesi; aşırı alım/satım bölgelerini ölçer.',
      chart:'70 üstü aşırı alım, 30 altı aşırı satım kabul edilir. Fiyatla uyumsuzluk (divergence) önemli sinyaldir.',
      trader:'Momentumun gücünü ve olası tükenmeyi değerlendirmeye yardımcı olur.',
      mistake:'Güçlü trendde "RSI 70 oldu, satayım" demek. Trendde RSI uzun süre aşırı bölgede kalabilir.',
      events:['Momentum','Risk'] }),
    L({ id:'macd', title:'MACD', cat:'gosterge', level:'temel',
      short:'İki hareketli ortalamanın farkıyla trend ve momentum ölçen gösterge.',
      chart:'MACD çizgisi sinyal çizgisini yukarı keserse pozitif, aşağı keserse negatif momentum. Histogram ivmeyi gösterir.',
      trader:'Trend yönü ve momentum değişimini birlikte okumayı sağlar.',
      mistake:'Yatay piyasada MACD kesişimlerine güvenmek; çok sık yanlış sinyal üretir.',
      events:['Momentum'] }),
    L({ id:'ema', title:'EMA — Üssel Hareketli Ortalama', cat:'gosterge', level:'temel',
      short:'Son fiyatlara daha çok ağırlık veren hareketli ortalama.',
      chart:'Fiyatın EMA üstünde olması yükseliş, altında olması düşüş eğilimi. EMA\'ların dizilimi trend gücünü gösterir.',
      trader:'Trend yönü ve dinamik destek/direnç olarak kullanılır.',
      mistake:'Yatay piyasada EMA kesişimleriyle alım satım yapıp testere hareketinde zarar etmek.',
      events:['Momentum'] }),
    L({ id:'bollinger', title:'Bollinger Bands', cat:'gosterge', level:'orta',
      short:'Ortalama etrafında volatiliteye göre genişleyip daralan bantlar.',
      chart:'Bantlar daralırsa (squeeze) düşük volatilite + yaklaşan hareket; genişlerse yüksek volatilite. Fiyat bantları test eder.',
      trader:'Volatilite sıkışmasını ve olası patlama (breakout) anlarını yakalamaya yarar.',
      mistake:'Banda değdi diye ters işlem açmak. Güçlü trendde fiyat bant boyunca yürüyebilir.',
      events:['Squeeze','Breakout'] }),
    L({ id:'atr', title:'ATR — Ortalama Gerçek Aralık', cat:'gosterge', level:'orta',
      short:'Volatiliteyi ölçen gösterge; ortalama fiyat hareket genişliğini verir.',
      chart:'Yön vermez, sadece hareket büyüklüğünü ölçer. Yüksek ATR = geniş mumlar, düşük ATR = sıkışma.',
      trader:'Stop mesafesi ve pozisyon büyüklüğü ayarlamada referans olarak kullanılır.',
      mistake:'ATR\'yi yön sinyali sanmak. ATR sadece volatilite ölçer, yön belirtmez.',
      events:['Squeeze','Risk'] }),
    L({ id:'volume', title:'Volume (Hacim)', cat:'gosterge', level:'temel',
      short:'Belirli sürede işlem gören miktar; hareketin gücünü teyit eder.',
      chart:'Kırılım yüksek hacimle gelirse güçlü, düşük hacimle gelirse şüphelidir. Hacimsiz yükseliş zayıftır.',
      trader:'Bir hareketin arkasında gerçek ilgi olup olmadığını anlamaya yardımcı olur.',
      mistake:'Fiyat hareketine bakıp hacmi yok saymak. Hacim teyit aracıdır.',
      events:['Open Interest','Breakout','Momentum'] }),

    // ── 4. FUTURES TEMELLERİ ────────────────────────────────────────
    L({ id:'funding', title:'Funding Rate', cat:'futures', level:'orta',
      short:'Perpetual futures\'ta long ve short tarafların birbirine ödediği periyodik ücret.',
      chart:'Pozitif funding: longlar shortlara öder (long kalabalık). Negatif: tersine. Aşırı değerler kalabalıklaşmayı gösterir.',
      trader:'Bir tarafın aşırı kalabalıklaştığını ve ters hareket riskini değerlendirmeye yardımcı olur.',
      mistake:'Sadece funding\'e bakıp pozisyon almak. Funding tek başına yön vermez.',
      events:['Funding','Risk'] }),
    L({ id:'open-interest', title:'Open Interest (OI)', cat:'futures', level:'orta',
      short:'Açık duran toplam futures sözleşme sayısı; piyasaya giren para/ilgi.',
      chart:'Fiyatla birlikte OI artarsa trend güçlü; fiyat artarken OI düşerse pozisyon kapanışı (zayıflık) olabilir.',
      trader:'Bir hareketin yeni para ile mi yoksa kapanışlarla mı oluştuğunu ayırt etmeye yarar.',
      mistake:'OI artışını tek başına yükseliş sinyali sanmak; yön için fiyatla birlikte okunmalı.',
      events:['Open Interest'] }),
    L({ id:'liquidation', title:'Liquidation (Tasfiye)', cat:'futures', level:'orta',
      short:'Marjin yetersizliğinde pozisyonun borsa tarafından zorla kapatılması.',
      chart:'Yoğun tasfiye bölgeleri sert, ani fitilli hareketler yaratır. Likidite avı sonrası dönüşler sık görülür.',
      trader:'Aşırı kaldıraçlı bölgelerde zincirleme tasfiye riskini anlamaya yardımcı olur.',
      mistake:'Yüksek kaldıraçla likidasyon fiyatını dar tutmak; küçük fitil bile pozisyonu siler.',
      events:['Risk','Liquidity'] }),
    L({ id:'long-short-ratio', title:'Long/Short Ratio', cat:'futures', level:'orta',
      short:'Long ve short pozisyon oranı; piyasa duyarlılığının kabaca ölçüsü.',
      chart:'Aşırı long ağırlık genelde "kalabalık long" riskini, aşırı short tersini gösterir. Contrarian okunabilir.',
      trader:'Kalabalığın hangi tarafta olduğunu ve olası sıkışmayı değerlendirmeye yarar.',
      mistake:'Oranı kesin sinyal sanmak; veri kaynağına göre değişir, tek başına yetersizdir.',
      events:['Funding','Risk'] }),
    L({ id:'leverage', title:'Leverage (Kaldıraç)', cat:'futures', level:'temel',
      short:'Az teminatla büyük pozisyon açma; kâr ve zararı aynı oranda büyütür.',
      chart:'Kaldıraç grafikte görünmez ama likidasyon mesafeni belirler. Yüksek kaldıraç = dar likidasyon.',
      trader:'Risk yönetiminin temelidir; pozisyon büyüklüğü ve hayatta kalma süresini belirler.',
      mistake:'Yüksek kaldıracı "daha çok kâr" sanmak. Asıl belirleyici pozisyon büyüklüğü ve stop\'tur.',
      events:['Risk'] }),
    L({ id:'risk-reward', title:'Risk / Reward (R/R)', cat:'futures', level:'temel',
      short:'Alınan riskin, hedeflenen kazanca oranı (ör. 1:2).',
      chart:'Giriş–Stop arası risk, Giriş–Hedef arası ödül. 1:2 = 1 birim risk, 2 birim hedef.',
      trader:'Düşük isabetle bile uzun vadede pozitif kalmayı sağlayan en temel kavramdır.',
      mistake:'R/R\'yi hesaba katmadan "iyi setup" diye girmek. Kötü R/R, yüksek isabeti bile eritir.',
      events:['Risk'] }),

    // ── 5. MARKET YAPISI ────────────────────────────────────────────
    L({ id:'trend', title:'Trend', cat:'yapi', level:'temel',
      short:'Fiyatın belirli bir yönde (yukarı/aşağı/yatay) ardışık hareketi.',
      chart:'Yükseliş: yükselen tepe ve dipler (HH/HL). Düşüş: alçalan tepe ve dipler (LH/LL). Yatay: belirsiz.',
      trader:'"Trend dosttur" — yön belirleme ve işlem tarafı seçmenin temelidir.',
      mistake:'Yatay piyasayı trend sanıp her harekette taraf seçmek.',
      events:['Momentum','Breakout'] }),
    L({ id:'sr', title:'Support / Resistance', cat:'yapi', level:'temel',
      short:'Fiyatın tepki verdiği destek (dip) ve direnç (tepe) seviyeleri.',
      chart:'Birden çok kez test edilen seviyeler güçlenir. Kırılan direnç desteğe, kırılan destek dirence dönebilir.',
      trader:'Giriş, stop ve hedef yerleşiminde en sık kullanılan referanslardır.',
      mistake:'Seviyeleri tek bir çizgi sanmak; aslında bölgedir, birebir fiyat beklenmez.',
      events:['Breakout','Equal High','Equal Low'] }),
    L({ id:'breakout', title:'Breakout (Kırılım)', cat:'yapi', level:'temel',
      short:'Fiyatın önemli bir destek/direnç seviyesini aşması.',
      chart:'Seviye hacimle birlikte kırılır. Güçlü kırılımı genelde retest (geri test) izler.',
      trader:'Yeni bir hareketin başlangıcı olabilir; yön ve hacim teyidi önemlidir.',
      mistake:'Her kırılıma anında girmek. Hacimsiz/teyitsiz kırılımlar sahte olabilir.',
      events:['Breakout','Momentum'] }),
    L({ id:'retest', title:'Retest (Geri Test)', cat:'yapi', level:'orta',
      short:'Kırılan seviyenin yeni yönden tekrar test edilmesi.',
      chart:'Direnç kırıldıktan sonra fiyat geri gelip o seviyeyi destek olarak test eder, sonra devam eder.',
      trader:'Daha güvenli, teyitli giriş fırsatı sunan klasik bir yapıdır.',
      mistake:'Retest beklerken kaçan trene üzülüp teyitsiz, geç girişler yapmak.',
      events:['Breakout'] }),
    L({ id:'fake-breakout', title:'Fake Breakout (Sahte Kırılım)', cat:'yapi', level:'orta',
      short:'Seviyenin kısa süre aşılıp hemen geri dönülmesi; tuzak hareket.',
      chart:'Fiyat seviyeyi geçer, stoplar tetiklenir, sonra hızla geri döner (genelde uzun fitil).',
      trader:'Likidite avı veya tuzak olabilir; ters yönde fırsat doğurabilir.',
      mistake:'İlk kırılımda hemen girmek. Sahte kırılım, teyitsiz girişlerin en sık zarar nedenidir.',
      events:['Risk','Liquidity'] }),
    L({ id:'momentum', title:'Momentum', cat:'yapi', level:'temel',
      short:'Fiyat hareketinin hızı ve gücü.',
      chart:'Genişleyen mumlar, artan hacim ve hızlanan eğim güçlü momentumu gösterir. Daralma zayıflamadır.',
      trader:'Hareketin sürdürülebilir olup olmadığını ve giriş zamanlamasını değerlendirmeye yarar.',
      mistake:'Zirve momentumda "daha gider" diye geç girmek; momentum tükenince sert dönüş gelir.',
      events:['Momentum'] }),
  ];

  window.VDAcademyData = { categories, lessons };
})();
