// ════════════════════════════════════════════════════════════════════
// ui/academy/academy-data.js  — VD ACADEMY ders verisi (Phase 1)
//
// Statik içerik kaynağı. window.VDAcademyData = { categories, lessons }.
// Her ders: { id, title, cat, level, short, chart, trader, mistake, events }
//   level : 'temel' | 'orta' | 'ileri'
//   events: bağlı Timeline event türleri (etiket) — event-lesson-map ile eşleşir
// Eğitim amaçlıdır; yatırım tavsiyesi değildir.
// ════════════════════════════════════════════════════════════════════
(function () {
  'use strict';
  function _t(k,v,f){return (window.VDt)?window.VDt(k,v,f):(f!=null?f:k);}

  const categories = [
    { id: 'formasyon', label: _t('acd.cat.formasyon',null,'Formasyonlar'), icon: '📐' },
    { id: 'smc',       label: 'Smart Money Concepts', icon: '💧' },
    { id: 'gosterge',  label: _t('acd.cat.gosterge',null,'Teknik Göstergeler'), icon: '📊' },
    { id: 'futures',   label: _t('acd.cat.futures',null,'Futures Temelleri'), icon: '⚙️' },
    { id: 'yapi',      label: _t('acd.cat.yapi',null,'Market Yapısı'), icon: '🏛️' },
  ];

  const L = (o) => o; // kısa yardımcı

  const lessons = [
    // ── 1. FORMASYONLAR ──────────────────────────────────────────────
    L({ id:'obo', title:_t('acd.obo.title',null,'Omuz Baş Omuz'), cat:'formasyon', level:'orta',
      short:_t('acd.obo.short',null,'Yükseliş trendinin sonunda görülen, üç tepeden oluşan dönüş formasyonu.'),
      chart:_t('acd.obo.chart',null,'Ortadaki tepe (baş) iki yandaki tepelerden (omuzlar) daha yüksektir. Omuzların diplerini birleştiren "boyun çizgisi" kırıldığında formasyon teyit olur.'),
      trader:_t('acd.obo.trader',null,'Yükselişin bittiğine ve aşağı dönüşe geçilebileceğine dair güçlü bir ipucu sayılır.'),
      mistake:_t('acd.obo.mistake',null,'Boyun çizgisi kırılmadan formasyonu "tamamlandı" saymak. Teyit olmadan pozisyon almak erken karardır.'),
      events:['Risk','Breakout'] }),
    L({ id:'ters-obo', title:_t('acd.ters-obo.title',null,'Ters Omuz Baş Omuz'), cat:'formasyon', level:'orta',
      short:_t('acd.ters-obo.short',null,'Düşüş trendinin sonunda görülen, üç dipten oluşan yukarı dönüş formasyonu.'),
      chart:_t('acd.ters-obo.chart',null,'Ortadaki dip (baş) en derindir; iki yandaki dipler (omuzlar) daha sığdır. Boyun çizgisi yukarı kırıldığında teyit olur.'),
      trader:_t('acd.ters-obo.trader',null,'Düşüşün zayıfladığına ve yukarı dönüş ihtimaline işaret edebilir.'),
      mistake:_t('acd.ters-obo.mistake',null,'Hacim teyidi olmadan kırılıma güvenmek. Zayıf hacimli kırılımlar sahte olabilir.'),
      events:['Breakout'] }),
    L({ id:'cekic', title:_t('acd.cekic.title',null,'Çekiç Mum'), cat:'formasyon', level:'temel',
      short:_t('acd.cekic.short',null,'Düşüşün dibinde oluşan, uzun alt fitilli, küçük gövdeli dönüş mumu.'),
      chart:_t('acd.cekic.chart',null,'Gövde mumun üst kısmındadır, alt fitil gövdenin en az iki katıdır. Satıcıların aşağı ittiği ama alıcıların geri topladığı anlamına gelir.'),
      trader:_t('acd.cekic.trader',null,'Dip bölgesinde alıcı ilgisinin döndüğüne dair erken bir sinyal olabilir.'),
      mistake:_t('acd.cekic.mistake',null,'Tek bir çekiç mumu kesin dönüş sanmak. Teyit için sonraki mumu beklemek gerekir.'),
      events:['Liquidity','Smart Money'] }),
    L({ id:'ters-cekic', title:_t('acd.ters-cekic.title',null,'Ters Çekiç'), cat:'formasyon', level:'temel',
      short:_t('acd.ters-cekic.short',null,'Düşüş sonrası oluşan, uzun üst fitilli küçük gövdeli mum.'),
      chart:_t('acd.ters-cekic.chart',null,'Gövde altta, üst fitil uzundur. Alıcıların yukarı denediği ama henüz teyit gelmediği bir geçiş mumudur.'),
      trader:_t('acd.ters-cekic.trader',null,'Olası dönüşün habercisi olabilir ama tek başına zayıf bir sinyaldir.'),
      mistake:_t('acd.ters-cekic.mistake',null,'Ters çekici tepe formasyonu (shooting star) ile karıştırmak. Konum (dip mi tepe mi) belirleyicidir.'),
      events:['Liquidity'] }),
    L({ id:'yutan', title:_t('acd.yutan.title',null,'Yutan Mum (Engulfing)'), cat:'formasyon', level:'temel',
      short:_t('acd.yutan.short',null,'Önceki mumun gövdesini tamamen kapsayan ters yönlü güçlü mum.'),
      chart:_t('acd.yutan.chart',null,'Boğa yutan: küçük kırmızı mumun ardından onu tümüyle saran büyük yeşil mum. Ayı yutan tam tersi.'),
      trader:_t('acd.yutan.trader',null,'Yön değişiminde momentumun el değiştirdiğine işaret edebilir.'),
      mistake:_t('acd.yutan.mistake',null,'Sadece gövdeye bakıp hacmi göz ardı etmek. Hacimsiz yutan mum güvenilmezdir.'),
      events:['Momentum','Smart Money'] }),
    L({ id:'doji', title:'Doji', cat:'formasyon', level:'temel',
      short:_t('acd.doji.short',null,'Açılış ve kapanışın neredeyse eşit olduğu kararsızlık mumu.'),
      chart:_t('acd.doji.chart',null,'Çok küçük veya neredeyse yok gövde, iki yanda fitiller. Alıcı ve satıcının dengelendiğini gösterir.'),
      trader:_t('acd.doji.trader',null,'Trendin duraksadığına; devam veya dönüş öncesi kararsızlığa işaret eder.'),
      mistake:_t('acd.doji.mistake',null,'Her doji\'yi dönüş sanmak. Doji tek başına yön vermez, bağlam şarttır.'),
      events:['Momentum'] }),
    L({ id:'ucgen', title:_t('acd.ucgen.title',null,'Üçgen Formasyonları'), cat:'formasyon', level:'orta',
      short:_t('acd.ucgen.short',null,'Fiyatın daralan bir aralıkta sıkıştığı, kırılım öncesi yapı.'),
      chart:_t('acd.ucgen.chart',null,'Yükselen, alçalan veya simetrik üçgen. Tepe ve dipler birbirine yaklaşır; kırılım genelde sıkışma sonunda gelir.'),
      trader:_t('acd.ucgen.trader',null,'Yaklaşan büyük hareketin habercisidir; yön kırılımla belli olur.'),
      mistake:_t('acd.ucgen.mistake',null,'Kırılım yönünü önceden tahmin edip erken girmek. Üçgen yön vermez, kırılım verir.'),
      events:['Squeeze','Breakout'] }),
    L({ id:'bayrak', title:_t('acd.bayrak.title',null,'Bayrak / Flama'), cat:'formasyon', level:'orta',
      short:_t('acd.bayrak.short',null,'Güçlü bir hareketin ardından gelen kısa soluklanma ve devam formasyonu.'),
      chart:_t('acd.bayrak.chart',null,'Sert yükseliş/düşüş (direk) sonrası küçük eğimli kanal (bayrak) veya küçük üçgen (flama). Trend yönünde kırılır.'),
      trader:_t('acd.bayrak.trader',null,'Mevcut trendin devam etme ihtimaline işaret eden bir dinlenme molasıdır.'),
      mistake:_t('acd.bayrak.mistake',null,'Bayrağı dönüş sanmak. Bayrak genelde trend yönünde devam eder.'),
      events:['Momentum','Breakout'] }),
    L({ id:'ikili-tepe', title:_t('acd.ikili-tepe.title',null,'İkili Tepe'), cat:'formasyon', level:'orta',
      short:_t('acd.ikili-tepe.short',null,'Aynı seviyede iki kez test edilen tepe; aşağı dönüş formasyonu.'),
      chart:_t('acd.ikili-tepe.chart',null,'İki benzer yükseklikte tepe ("M" şekli), aradaki dibin (boyun) kırılması teyit verir.'),
      trader:_t('acd.ikili-tepe.trader',null,'Direncin aşılamadığına ve satış baskısının arttığına işaret eder.'),
      mistake:_t('acd.ikili-tepe.mistake',null,'İki tepe görünce hemen short açmak. Boyun çizgisi kırılmadan teyit yoktur.'),
      events:['Equal High','Risk'] }),
    L({ id:'ikili-dip', title:_t('acd.ikili-dip.title',null,'İkili Dip'), cat:'formasyon', level:'orta',
      short:_t('acd.ikili-dip.short',null,'Aynı seviyede iki kez test edilen dip; yukarı dönüş formasyonu.'),
      chart:_t('acd.ikili-dip.chart',null,'İki benzer derinlikte dip ("W" şekli), aradaki tepenin kırılması teyit verir.'),
      trader:_t('acd.ikili-dip.trader',null,'Desteğin korunduğuna ve alıcı ilgisinin döndüğüne işaret edebilir.'),
      mistake:_t('acd.ikili-dip.mistake',null,'İkinci dibin ilkinden belirgin aşağıda olmasını göz ardı etmek — o zaman formasyon bozulur.'),
      events:['Equal Low'] }),

    // ── 2. SMART MONEY CONCEPTS ──────────────────────────────────────
    L({ id:'bos', title:'BOS — Break of Structure', cat:'smc', level:'ileri',
      short:_t('acd.bos.short',null,'Mevcut trend yönünde bir önceki tepe/dibin kırılması; trendin devamı.'),
      chart:_t('acd.bos.chart',null,'Yükselişte son tepenin yukarı kırılması (HH), düşüşte son dibin aşağı kırılması (LL) BOS sayılır.'),
      trader:_t('acd.bos.trader',null,'Trendin hâlâ güçlü ve geçerli olduğunu teyit eder.'),
      mistake:_t('acd.bos.mistake',null,'Her küçük kırılımı BOS sanmak. Anlamlı yapı seviyeleri kullanılmalı.'),
      events:['BOS','Breakout'] }),
    L({ id:'choch', title:'CHoCH — Change of Character', cat:'smc', level:'ileri',
      short:_t('acd.choch.short',null,'Trendin karakterinin değiştiği ilk kırılım; olası dönüşün erken işareti.'),
      chart:_t('acd.choch.chart',null,'Yükselişte ilk kez bir önceki dibin aşağı kırılması (veya tersi). BOS\'un aksine trend YÖNÜNE karşı gelir.'),
      trader:_t('acd.choch.trader',null,'Trendin zayıflayıp dönebileceğine dair ilk uyarıdır.'),
      mistake:_t('acd.choch.mistake',null,'CHoCH\'u kesin dönüş sanmak. Teyit için yapı değişiminin devamı gerekir.'),
      events:['CHoCH'] }),
    L({ id:'order-block', title:'Order Block', cat:'smc', level:'ileri',
      short:_t('acd.order-block.short',null,'Kurumsal emirlerin yoğunlaştığı, sert hareket öncesi son zıt yönlü mum bölgesi.'),
      chart:_t('acd.order-block.chart',null,'Güçlü yükseliş öncesi son düşüş mumu (boğa OB) veya tersi. Fiyat geri döndüğünde tepki verebilir.'),
      trader:_t('acd.order-block.trader',null,'Akıllı paranın bıraktığı izlerin tepki/giriş bölgesi olabileceğini gösterir.'),
      mistake:_t('acd.order-block.mistake',null,'Her mumu order block ilan etmek. OB, belirgin dengesizlik (impulse) ile birlikte anlamlıdır.'),
      events:['Order Block','Smart Money'] }),
    L({ id:'fvg', title:'Fair Value Gap (FVG)', cat:'smc', level:'ileri',
      short:_t('acd.fvg.short',null,'Üç mumda oluşan, fiyatın hızlı geçtiği ve sonradan doldurmaya eğilimli boşluk.'),
      chart:_t('acd.fvg.chart',null,'Orta mumun fitillerinin yan mumlarla örtüşmediği boşluk. Fiyat genelde bu boşluğu test etmeye döner.'),
      trader:_t('acd.fvg.trader',null,'Dengesizliğin bulunduğu, geri çekilmede tepki beklenebilecek bölgedir.'),
      mistake:_t('acd.fvg.mistake',null,'Her FVG\'nin mutlaka dolacağını varsaymak. Bazıları uzun süre dolmaz.'),
      events:['FVG','Smart Money'] }),
    L({ id:'liquidity-sweep', title:'Liquidity Sweep', cat:'smc', level:'ileri',
      short:_t('acd.liquidity-sweep.short',null,'Likidite bölgesinin kısa süreli test edilip ters yöne dönülmesi.'),
      chart:_t('acd.liquidity-sweep.chart',null,'Önce son tepe/dip aşılır (stoplar tetiklenir), ardından hızlı geri dönüş olur.'),
      trader:_t('acd.liquidity-sweep.trader',null,'Stop avı veya yön dönüşü ihtimali anlamına gelebilir.'),
      mistake:_t('acd.liquidity-sweep.mistake',null,'Her fitil liquidity sweep değildir; hacim ve bağlam olmadan yorumlamak yanıltır.'),
      events:['Liquidity','Risk','Smart Money'] }),
    L({ id:'equal-high', title:_t('acd.equal-high.title',null,'Equal High (Eşit Tepe)'), cat:'smc', level:'orta',
      short:_t('acd.equal-high.short',null,'Aynı seviyede oluşan tepeler; üstünde likidite biriken bölge.'),
      chart:_t('acd.equal-high.chart',null,'Yan yana benzer yükseklikte tepeler. Üstlerinde stop emirleri toplanır, hedef likidite olabilir.'),
      trader:_t('acd.equal-high.trader',null,'Fiyatın bu seviyeyi süpürmeye (sweep) gelebileceğine işaret eder.'),
      mistake:_t('acd.equal-high.mistake',null,'Eşit tepeyi kesin direnç sanmak; çoğu zaman likidite avı için kırılır.'),
      events:['Equal High','Liquidity'] }),
    L({ id:'equal-low', title:_t('acd.equal-low.title',null,'Equal Low (Eşit Dip)'), cat:'smc', level:'orta',
      short:_t('acd.equal-low.short',null,'Aynı seviyede oluşan dipler; altında likidite biriken bölge.'),
      chart:_t('acd.equal-low.chart',null,'Benzer derinlikte dipler. Altlarında stoplar toplanır, sweep hedefi olabilir.'),
      trader:_t('acd.equal-low.trader',null,'Fiyatın bu dibi süpürüp dönme ihtimaline işaret eder.'),
      mistake:_t('acd.equal-low.mistake',null,'Eşit dibi kesin destek saymak; likidite için aşağı süpürülebilir.'),
      events:['Equal Low','Liquidity'] }),
    L({ id:'stop-hunt', title:'Stop Hunt', cat:'smc', level:'ileri',
      short:_t('acd.stop-hunt.short',null,'Yoğun stop bölgelerinin kasıtlı tetiklenmesiyle oluşan kısa, sert hareket.'),
      chart:_t('acd.stop-hunt.chart',null,'Belirgin seviye hızlıca aşılır, stoplar tetiklenir, sonra fiyat ters döner.'),
      trader:_t('acd.stop-hunt.trader',null,'Zorla çıkarılan pozisyonlar ardından yön dönüşü gelebilir.'),
      mistake:_t('acd.stop-hunt.mistake',null,'Stop hunt\'ı normal kırılımla karıştırıp trend yönünde girmek.'),
      events:['Risk','Liquidity'] }),

    // ── 3. TEKNİK GÖSTERGELER ───────────────────────────────────────
    L({ id:'rsi', title:'RSI', cat:'gosterge', level:'temel',
      short:_t('acd.rsi.short',null,'0–100 arası momentum göstergesi; aşırı alım/satım bölgelerini ölçer.'),
      chart:_t('acd.rsi.chart',null,'70 üstü aşırı alım, 30 altı aşırı satım kabul edilir. Fiyatla uyumsuzluk (divergence) önemli sinyaldir.'),
      trader:_t('acd.rsi.trader',null,'Momentumun gücünü ve olası tükenmeyi değerlendirmeye yardımcı olur.'),
      mistake:_t('acd.rsi.mistake',null,'Güçlü trendde "RSI 70 oldu, satayım" demek. Trendde RSI uzun süre aşırı bölgede kalabilir.'),
      events:['Momentum','Risk'] }),
    L({ id:'macd', title:'MACD', cat:'gosterge', level:'temel',
      short:_t('acd.macd.short',null,'İki hareketli ortalamanın farkıyla trend ve momentum ölçen gösterge.'),
      chart:_t('acd.macd.chart',null,'MACD çizgisi sinyal çizgisini yukarı keserse pozitif, aşağı keserse negatif momentum. Histogram ivmeyi gösterir.'),
      trader:_t('acd.macd.trader',null,'Trend yönü ve momentum değişimini birlikte okumayı sağlar.'),
      mistake:_t('acd.macd.mistake',null,'Yatay piyasada MACD kesişimlerine güvenmek; çok sık yanlış sinyal üretir.'),
      events:['Momentum'] }),
    L({ id:'ema', title:_t('acd.ema.title',null,'EMA — Üssel Hareketli Ortalama'), cat:'gosterge', level:'temel',
      short:_t('acd.ema.short',null,'Son fiyatlara daha çok ağırlık veren hareketli ortalama.'),
      chart:_t('acd.ema.chart',null,'Fiyatın EMA üstünde olması yükseliş, altında olması düşüş eğilimi. EMA\'ların dizilimi trend gücünü gösterir.'),
      trader:_t('acd.ema.trader',null,'Trend yönü ve dinamik destek/direnç olarak kullanılır.'),
      mistake:_t('acd.ema.mistake',null,'Yatay piyasada EMA kesişimleriyle alım satım yapıp testere hareketinde zarar etmek.'),
      events:['Momentum'] }),
    L({ id:'bollinger', title:'Bollinger Bands', cat:'gosterge', level:'orta',
      short:_t('acd.bollinger.short',null,'Ortalama etrafında volatiliteye göre genişleyip daralan bantlar.'),
      chart:_t('acd.bollinger.chart',null,'Bantlar daralırsa (squeeze) düşük volatilite + yaklaşan hareket; genişlerse yüksek volatilite. Fiyat bantları test eder.'),
      trader:_t('acd.bollinger.trader',null,'Volatilite sıkışmasını ve olası patlama (breakout) anlarını yakalamaya yarar.'),
      mistake:_t('acd.bollinger.mistake',null,'Banda değdi diye ters işlem açmak. Güçlü trendde fiyat bant boyunca yürüyebilir.'),
      events:['Squeeze','Breakout'] }),
    L({ id:'atr', title:_t('acd.atr.title',null,'ATR — Ortalama Gerçek Aralık'), cat:'gosterge', level:'orta',
      short:_t('acd.atr.short',null,'Volatiliteyi ölçen gösterge; ortalama fiyat hareket genişliğini verir.'),
      chart:_t('acd.atr.chart',null,'Yön vermez, sadece hareket büyüklüğünü ölçer. Yüksek ATR = geniş mumlar, düşük ATR = sıkışma.'),
      trader:_t('acd.atr.trader',null,'Stop mesafesi ve pozisyon büyüklüğü ayarlamada referans olarak kullanılır.'),
      mistake:_t('acd.atr.mistake',null,'ATR\'yi yön sinyali sanmak. ATR sadece volatilite ölçer, yön belirtmez.'),
      events:['Squeeze','Risk'] }),
    L({ id:'volume', title:_t('acd.volume.title',null,'Volume (Hacim)'), cat:'gosterge', level:'temel',
      short:_t('acd.volume.short',null,'Belirli sürede işlem gören miktar; hareketin gücünü teyit eder.'),
      chart:_t('acd.volume.chart',null,'Kırılım yüksek hacimle gelirse güçlü, düşük hacimle gelirse şüphelidir. Hacimsiz yükseliş zayıftır.'),
      trader:_t('acd.volume.trader',null,'Bir hareketin arkasında gerçek ilgi olup olmadığını anlamaya yardımcı olur.'),
      mistake:_t('acd.volume.mistake',null,'Fiyat hareketine bakıp hacmi yok saymak. Hacim teyit aracıdır.'),
      events:['Open Interest','Breakout','Momentum'] }),

    // ── 4. FUTURES TEMELLERİ ────────────────────────────────────────
    L({ id:'funding', title:'Funding Rate', cat:'futures', level:'orta',
      short:_t('acd.funding.short',null,'Perpetual futures\'ta long ve short tarafların birbirine ödediği periyodik ücret.'),
      chart:_t('acd.funding.chart',null,'Pozitif funding: longlar shortlara öder (long kalabalık). Negatif: tersine. Aşırı değerler kalabalıklaşmayı gösterir.'),
      trader:_t('acd.funding.trader',null,'Bir tarafın aşırı kalabalıklaştığını ve ters hareket riskini değerlendirmeye yardımcı olur.'),
      mistake:_t('acd.funding.mistake',null,'Sadece funding\'e bakıp pozisyon almak. Funding tek başına yön vermez.'),
      events:['Funding','Risk'] }),
    L({ id:'open-interest', title:'Open Interest (OI)', cat:'futures', level:'orta',
      short:_t('acd.open-interest.short',null,'Açık duran toplam futures sözleşme sayısı; piyasaya giren para/ilgi.'),
      chart:_t('acd.open-interest.chart',null,'Fiyatla birlikte OI artarsa trend güçlü; fiyat artarken OI düşerse pozisyon kapanışı (zayıflık) olabilir.'),
      trader:_t('acd.open-interest.trader',null,'Bir hareketin yeni para ile mi yoksa kapanışlarla mı oluştuğunu ayırt etmeye yarar.'),
      mistake:_t('acd.open-interest.mistake',null,'OI artışını tek başına yükseliş sinyali sanmak; yön için fiyatla birlikte okunmalı.'),
      events:['Open Interest'] }),
    L({ id:'liquidation', title:_t('acd.liquidation.title',null,'Liquidation (Tasfiye)'), cat:'futures', level:'orta',
      short:_t('acd.liquidation.short',null,'Marjin yetersizliğinde pozisyonun borsa tarafından zorla kapatılması.'),
      chart:_t('acd.liquidation.chart',null,'Yoğun tasfiye bölgeleri sert, ani fitilli hareketler yaratır. Likidite avı sonrası dönüşler sık görülür.'),
      trader:_t('acd.liquidation.trader',null,'Aşırı kaldıraçlı bölgelerde zincirleme tasfiye riskini anlamaya yardımcı olur.'),
      mistake:_t('acd.liquidation.mistake',null,'Yüksek kaldıraçla likidasyon fiyatını dar tutmak; küçük fitil bile pozisyonu siler.'),
      events:['Risk','Liquidity'] }),
    L({ id:'long-short-ratio', title:'Long/Short Ratio', cat:'futures', level:'orta',
      short:_t('acd.long-short-ratio.short',null,'Long ve short pozisyon oranı; piyasa duyarlılığının kabaca ölçüsü.'),
      chart:_t('acd.long-short-ratio.chart',null,'Aşırı long ağırlık genelde "kalabalık long" riskini, aşırı short tersini gösterir. Contrarian okunabilir.'),
      trader:_t('acd.long-short-ratio.trader',null,'Kalabalığın hangi tarafta olduğunu ve olası sıkışmayı değerlendirmeye yarar.'),
      mistake:_t('acd.long-short-ratio.mistake',null,'Oranı kesin sinyal sanmak; veri kaynağına göre değişir, tek başına yetersizdir.'),
      events:['Funding','Risk'] }),
    L({ id:'leverage', title:_t('acd.leverage.title',null,'Leverage (Kaldıraç)'), cat:'futures', level:'temel',
      short:_t('acd.leverage.short',null,'Az teminatla büyük pozisyon açma; kâr ve zararı aynı oranda büyütür.'),
      chart:_t('acd.leverage.chart',null,'Kaldıraç grafikte görünmez ama likidasyon mesafeni belirler. Yüksek kaldıraç = dar likidasyon.'),
      trader:_t('acd.leverage.trader',null,'Risk yönetiminin temelidir; pozisyon büyüklüğü ve hayatta kalma süresini belirler.'),
      mistake:_t('acd.leverage.mistake',null,'Yüksek kaldıracı "daha çok kâr" sanmak. Asıl belirleyici pozisyon büyüklüğü ve stop\'tur.'),
      events:['Risk'] }),
    L({ id:'risk-reward', title:'Risk / Reward (R/R)', cat:'futures', level:'temel',
      short:_t('acd.risk-reward.short',null,'Alınan riskin, hedeflenen kazanca oranı (ör. 1:2).'),
      chart:_t('acd.risk-reward.chart',null,'Giriş–Stop arası risk, Giriş–Hedef arası ödül. 1:2 = 1 birim risk, 2 birim hedef.'),
      trader:_t('acd.risk-reward.trader',null,'Düşük isabetle bile uzun vadede pozitif kalmayı sağlayan en temel kavramdır.'),
      mistake:_t('acd.risk-reward.mistake',null,'R/R\'yi hesaba katmadan "iyi setup" diye girmek. Kötü R/R, yüksek isabeti bile eritir.'),
      events:['Risk'] }),

    // ── 5. MARKET YAPISI ────────────────────────────────────────────
    L({ id:'trend', title:'Trend', cat:'yapi', level:'temel',
      short:_t('acd.trend.short',null,'Fiyatın belirli bir yönde (yukarı/aşağı/yatay) ardışık hareketi.'),
      chart:_t('acd.trend.chart',null,'Yükseliş: yükselen tepe ve dipler (HH/HL). Düşüş: alçalan tepe ve dipler (LH/LL). Yatay: belirsiz.'),
      trader:_t('acd.trend.trader',null,'"Trend dosttur" — yön belirleme ve işlem tarafı seçmenin temelidir.'),
      mistake:_t('acd.trend.mistake',null,'Yatay piyasayı trend sanıp her harekette taraf seçmek.'),
      events:['Momentum','Breakout'] }),
    L({ id:'sr', title:'Support / Resistance', cat:'yapi', level:'temel',
      short:_t('acd.sr.short',null,'Fiyatın tepki verdiği destek (dip) ve direnç (tepe) seviyeleri.'),
      chart:_t('acd.sr.chart',null,'Birden çok kez test edilen seviyeler güçlenir. Kırılan direnç desteğe, kırılan destek dirence dönebilir.'),
      trader:_t('acd.sr.trader',null,'Giriş, stop ve hedef yerleşiminde en sık kullanılan referanslardır.'),
      mistake:_t('acd.sr.mistake',null,'Seviyeleri tek bir çizgi sanmak; aslında bölgedir, birebir fiyat beklenmez.'),
      events:['Breakout','Equal High','Equal Low'] }),
    L({ id:'breakout', title:_t('acd.breakout.title',null,'Breakout (Kırılım)'), cat:'yapi', level:'temel',
      short:_t('acd.breakout.short',null,'Fiyatın önemli bir destek/direnç seviyesini aşması.'),
      chart:_t('acd.breakout.chart',null,'Seviye hacimle birlikte kırılır. Güçlü kırılımı genelde retest (geri test) izler.'),
      trader:_t('acd.breakout.trader',null,'Yeni bir hareketin başlangıcı olabilir; yön ve hacim teyidi önemlidir.'),
      mistake:_t('acd.breakout.mistake',null,'Her kırılıma anında girmek. Hacimsiz/teyitsiz kırılımlar sahte olabilir.'),
      events:['Breakout','Momentum'] }),
    L({ id:'retest', title:_t('acd.retest.title',null,'Retest (Geri Test)'), cat:'yapi', level:'orta',
      short:_t('acd.retest.short',null,'Kırılan seviyenin yeni yönden tekrar test edilmesi.'),
      chart:_t('acd.retest.chart',null,'Direnç kırıldıktan sonra fiyat geri gelip o seviyeyi destek olarak test eder, sonra devam eder.'),
      trader:_t('acd.retest.trader',null,'Daha güvenli, teyitli giriş fırsatı sunan klasik bir yapıdır.'),
      mistake:_t('acd.retest.mistake',null,'Retest beklerken kaçan trene üzülüp teyitsiz, geç girişler yapmak.'),
      events:['Breakout'] }),
    L({ id:'fake-breakout', title:_t('acd.fake-breakout.title',null,'Fake Breakout (Sahte Kırılım)'), cat:'yapi', level:'orta',
      short:_t('acd.fake-breakout.short',null,'Seviyenin kısa süre aşılıp hemen geri dönülmesi; tuzak hareket.'),
      chart:_t('acd.fake-breakout.chart',null,'Fiyat seviyeyi geçer, stoplar tetiklenir, sonra hızla geri döner (genelde uzun fitil).'),
      trader:_t('acd.fake-breakout.trader',null,'Likidite avı veya tuzak olabilir; ters yönde fırsat doğurabilir.'),
      mistake:_t('acd.fake-breakout.mistake',null,'İlk kırılımda hemen girmek. Sahte kırılım, teyitsiz girişlerin en sık zarar nedenidir.'),
      events:['Risk','Liquidity'] }),
    L({ id:'momentum', title:'Momentum', cat:'yapi', level:'temel',
      short:_t('acd.momentum.short',null,'Fiyat hareketinin hızı ve gücü.'),
      chart:_t('acd.momentum.chart',null,'Genişleyen mumlar, artan hacim ve hızlanan eğim güçlü momentumu gösterir. Daralma zayıflamadır.'),
      trader:_t('acd.momentum.trader',null,'Hareketin sürdürülebilir olup olmadığını ve giriş zamanlamasını değerlendirmeye yarar.'),
      mistake:_t('acd.momentum.mistake',null,'Zirve momentumda "daha gider" diye geç girmek; momentum tükenince sert dönüş gelir.'),
      events:['Momentum'] }),
  ];

  window.VDAcademyData = { categories, lessons };
})();
